
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/natyo/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/natyo/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/natyo/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/natyo/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Versión de MSBuild 17.7.2+d6990bcfa para .NET Framework
      Compilación iniciada a las 20/02/2024 9:08:29 p. m..
      
      Proyecto "C:\\Users\\natyo\\OneDrive - Universidad EIA\\Escritorio\\POOH\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.vcxproj" en nodo 1 (destinos predeterminados).
      PrepareForBuild:
        Creando directorio "Debug\\".
        Creando directorio "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Se creará "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" porque se especificó "AlwaysCreate".
        Aplicando tarea Touch a "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\natyo\\OneDrive - Universidad EIA\\Escritorio\\POOH\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Se eliminará el archivo "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Aplicando tarea Touch a "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Compilación del proyecto terminada "C:\\Users\\natyo\\OneDrive - Universidad EIA\\Escritorio\\POOH\\CMakeFiles\\3.28.3\\CompilerIdC\\CompilerIdC.vcxproj" (destinos predeterminados).
      
      Compilación correcta.
          0 Advertencia(s)
          0 Errores
      
      Tiempo transcurrido 00:00:01.75
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/natyo/OneDrive - Universidad EIA/Escritorio/POOH/CMakeFiles/3.28.3/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/natyo/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/natyo/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/natyo/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Versión de MSBuild 17.7.2+d6990bcfa para .NET Framework
      Compilación iniciada a las 20/02/2024 9:08:31 p. m..
      
      Proyecto "C:\\Users\\natyo\\OneDrive - Universidad EIA\\Escritorio\\POOH\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" en nodo 1 (destinos predeterminados).
      PrepareForBuild:
        Creando directorio "Debug\\".
        Creando directorio "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Se creará "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild" porque se especificó "AlwaysCreate".
        Aplicando tarea Touch a "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\natyo\\OneDrive - Universidad EIA\\Escritorio\\POOH\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Se eliminará el archivo "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Aplicando tarea Touch a "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Compilación del proyecto terminada "C:\\Users\\natyo\\OneDrive - Universidad EIA\\Escritorio\\POOH\\CMakeFiles\\3.28.3\\CompilerIdCXX\\CompilerIdCXX.vcxproj" (destinos predeterminados).
      
      Compilación correcta.
          0 Advertencia(s)
          0 Errores
      
      Tiempo transcurrido 00:00:01.33
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/natyo/OneDrive - Universidad EIA/Escritorio/POOH/CMakeFiles/3.28.3/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/natyo/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/natyo/CMake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/natyo/OneDrive - Universidad EIA/Escritorio/POOH/CMakeFiles/CMakeScratch/TryCompile-l2a9uz"
      binary: "C:/Users/natyo/OneDrive - Universidad EIA/Escritorio/POOH/CMakeFiles/CMakeScratch/TryCompile-l2a9uz"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_C_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/natyo/OneDrive - Universidad EIA/Escritorio/POOH/CMakeFiles/CMakeScratch/TryCompile-l2a9uz'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_8911f.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Versión de MSBuild 17.7.2+d6990bcfa para .NET Framework
        Compilación iniciada a las 20/02/2024 9:08:32 p. m..
        
        Proyecto "C:\\Users\\natyo\\OneDrive - Universidad EIA\\Escritorio\\POOH\\CMakeFiles\\CMakeScratch\\TryCompile-l2a9uz\\cmTC_8911f.vcxproj" en nodo 1 (destinos predeterminados).
        PrepareForBuild:
          Creando directorio "cmTC_8911f.dir\\Debug\\".
          Creando directorio "C:\\Users\\natyo\\OneDrive - Universidad EIA\\Escritorio\\POOH\\CMakeFiles\\CMakeScratch\\TryCompile-l2a9uz\\Debug\\".
          Creando directorio "cmTC_8911f.dir\\Debug\\cmTC_8911f.tlog\\".
        InitializeBuildStatus:
          Se creará "cmTC_8911f.dir\\Debug\\cmTC_8911f.tlog\\unsuccessfulbuild" porque se especificó "AlwaysCreate".
          Aplicando tarea Touch a "cmTC_8911f.dir\\Debug\\cmTC_8911f.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_8911f.dir\\Debug\\\\" /Fd"cmTC_8911f.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Users\\natyo\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          Compilador de optimización de C/C++ de Microsoft (R) versión 19.37.32822 para x64
          CMakeCCompilerABI.c
          (C) Microsoft Corporation. Todos los derechos reservados.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_8911f.dir\\Debug\\\\" /Fd"cmTC_8911f.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Users\\natyo\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\natyo\\OneDrive - Universidad EIA\\Escritorio\\POOH\\CMakeFiles\\CMakeScratch\\TryCompile-l2a9uz\\Debug\\cmTC_8911f.exe" /INCREMENTAL /ILK:"cmTC_8911f.dir\\Debug\\cmTC_8911f.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/natyo/OneDrive - Universidad EIA/Escritorio/POOH/CMakeFiles/CMakeScratch/TryCompile-l2a9uz/Debug/cmTC_8911f.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/natyo/OneDrive - Universidad EIA/Escritorio/POOH/CMakeFiles/CMakeScratch/TryCompile-l2a9uz/Debug/cmTC_8911f.lib" /MACHINE:X64  /machine:x64 cmTC_8911f.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_8911f.vcxproj -> C:\\Users\\natyo\\OneDrive - Universidad EIA\\Escritorio\\POOH\\CMakeFiles\\CMakeScratch\\TryCompile-l2a9uz\\Debug\\cmTC_8911f.exe
        FinalizeBuildStatus:
          Se eliminará el archivo "cmTC_8911f.dir\\Debug\\cmTC_8911f.tlog\\unsuccessfulbuild".
          Aplicando tarea Touch a "cmTC_8911f.dir\\Debug\\cmTC_8911f.tlog\\cmTC_8911f.lastbuildstate".
        Compilación del proyecto terminada "C:\\Users\\natyo\\OneDrive - Universidad EIA\\Escritorio\\POOH\\CMakeFiles\\CMakeScratch\\TryCompile-l2a9uz\\cmTC_8911f.vcxproj" (destinos predeterminados).
        
        Compilación correcta.
            0 Advertencia(s)
            0 Errores
        
        Tiempo transcurrido 00:00:01.20
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/natyo/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/natyo/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/natyo/OneDrive - Universidad EIA/Escritorio/POOH/CMakeFiles/CMakeScratch/TryCompile-k8h02u"
      binary: "C:/Users/natyo/OneDrive - Universidad EIA/Escritorio/POOH/CMakeFiles/CMakeScratch/TryCompile-k8h02u"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_CXX_FLAGS_DEBUG: "/MDd /Zi /Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/natyo/OneDrive - Universidad EIA/Escritorio/POOH/CMakeFiles/CMakeScratch/TryCompile-k8h02u'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_3e105.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Versión de MSBuild 17.7.2+d6990bcfa para .NET Framework
        Compilación iniciada a las 20/02/2024 9:08:34 p. m..
        
        Proyecto "C:\\Users\\natyo\\OneDrive - Universidad EIA\\Escritorio\\POOH\\CMakeFiles\\CMakeScratch\\TryCompile-k8h02u\\cmTC_3e105.vcxproj" en nodo 1 (destinos predeterminados).
        PrepareForBuild:
          Creando directorio "cmTC_3e105.dir\\Debug\\".
          Creando directorio "C:\\Users\\natyo\\OneDrive - Universidad EIA\\Escritorio\\POOH\\CMakeFiles\\CMakeScratch\\TryCompile-k8h02u\\Debug\\".
          Creando directorio "cmTC_3e105.dir\\Debug\\cmTC_3e105.tlog\\".
        InitializeBuildStatus:
          Se creará "cmTC_3e105.dir\\Debug\\cmTC_3e105.tlog\\unsuccessfulbuild" porque se especificó "AlwaysCreate".
          Aplicando tarea Touch a "cmTC_3e105.dir\\Debug\\cmTC_3e105.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_3e105.dir\\Debug\\\\" /Fd"cmTC_3e105.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Users\\natyo\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          Compilador de optimización de C/C++ de Microsoft (R) versión 19.37.32822 para x64
          CMakeCXXCompilerABI.cpp
          (C) Microsoft Corporation. Todos los derechos reservados.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_3e105.dir\\Debug\\\\" /Fd"cmTC_3e105.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Users\\natyo\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\natyo\\OneDrive - Universidad EIA\\Escritorio\\POOH\\CMakeFiles\\CMakeScratch\\TryCompile-k8h02u\\Debug\\cmTC_3e105.exe" /INCREMENTAL /ILK:"cmTC_3e105.dir\\Debug\\cmTC_3e105.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/natyo/OneDrive - Universidad EIA/Escritorio/POOH/CMakeFiles/CMakeScratch/TryCompile-k8h02u/Debug/cmTC_3e105.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/natyo/OneDrive - Universidad EIA/Escritorio/POOH/CMakeFiles/CMakeScratch/TryCompile-k8h02u/Debug/cmTC_3e105.lib" /MACHINE:X64  /machine:x64 cmTC_3e105.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_3e105.vcxproj -> C:\\Users\\natyo\\OneDrive - Universidad EIA\\Escritorio\\POOH\\CMakeFiles\\CMakeScratch\\TryCompile-k8h02u\\Debug\\cmTC_3e105.exe
        FinalizeBuildStatus:
          Se eliminará el archivo "cmTC_3e105.dir\\Debug\\cmTC_3e105.tlog\\unsuccessfulbuild".
          Aplicando tarea Touch a "cmTC_3e105.dir\\Debug\\cmTC_3e105.tlog\\cmTC_3e105.lastbuildstate".
        Compilación del proyecto terminada "C:\\Users\\natyo\\OneDrive - Universidad EIA\\Escritorio\\POOH\\CMakeFiles\\CMakeScratch\\TryCompile-k8h02u\\cmTC_3e105.vcxproj" (destinos predeterminados).
        
        Compilación correcta.
            0 Advertencia(s)
            0 Errores
        
        Tiempo transcurrido 00:00:01.10
        
      exitCode: 0
...
